version: "3.9"

services:
  app:
    image: my-app:v1.0.1
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    networks:
      - my-node-app

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - my-node-app
    volumes:
      - db-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_DEFAULT_PORT: "80"
    networks:
      - my-node-app

volumes:
  db-data:

networks:
  my-node-app:
    driver: bridge
